### ISSUE TITLE
Create SECURITY file

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#105]
### Overview
Create SECURITY file

### Action Items
- [x] Click on link to [create new file](https://github.com/100Automations/Website/new/gh-pages)
- [x] Name the file SECURITY.md
- [x] Read the [community support file guide](https://github.com/100Automations/Website/blob/gh-pages/_guides/community-support-for-automations.md) for example of content
- [x] Include in the file: To report security issues, users should join the slack channel or email 100Automations@hackforla.org
- [x] Select second option - create a new branch
- [x] Create pull request, remember to include ```fixes #105``` in the pull request comment.

### Resources/Instructions
Screenshots for reference
![image](https://user-images.githubusercontent.com/75456721/108611323-7e850b80-7392-11eb-9275-4aa3f0a5d37b.png)

![image](https://user-images.githubusercontent.com/75456721/108611339-a5dbd880-7392-11eb-9c8c-8637e3e1dd35.png)

**Comment by henlatourrette** [comment]
I think I was able to create the file. It told me that since it didn't have any conflict with any existing branch it could be merged automatically. I clicked on the green "merge" button and it think it already closed this issue as well. I'm reopening now so that we can check it together @Olivia-Chiong
