### ISSUE TITLE
Add title cards for futureautomations project board

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#117]
### Overview
We need to add title cards for futureautomations project board so people viewing it can understand where the automations stands in the process.

### Action Items
- [x] Create title note cards that explains each column for the project board
- [x] Ensure the cards explain how to move to the next column

### Resources/Instructions
[futureautomations project board](https://github.com/100Automations/futureautomations/projects/1)

**Comment by NivenPrasad** [comment]
Hi @Olivia-Chiong, @ExperimentsInHonesty - I've added title cards to the [futureautomations project board](https://github.com/100Automations/futureautomations/projects/1). Some further comments from doing this:

- I see the futureautomations project board as user facing so I developed the notes with supporting UX for ideators and developers in mind
- Since it's user facing, it would be helpful to get it reviewed for clarity and sense by the whole team before a final pass by product

**Comment by NivenPrasad** [comment]
@nahyungkim1220, @superbunker @mdothman can you please provide feedback on whether the notes in the columns:

- make clear what the cards in the column contain
- there is a clear and easy to understand workflow from one column to the next

**Comment by ExperimentsInHonesty** [comment]
Done column
![Screen Shot 2021-01-06 at 4 54 42 PM](https://user-images.githubusercontent.com/37763229/103837126-e6300300-503f-11eb-8aff-c321ca6cf16c.png)

What is your plan for automations that turn out not to be created.  For instance the one that is in there now, didn't need to be created because it already exists.

**Comment by NivenPrasad** [comment]
Team reviewed the columns and we iterated on the workflow and cards.
