### ISSUE TITLE
Create a Want to contribute to an automation? guide

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#127]
### Overview
We need to create a guide for builders so there is a landing page and flow for the contributing builder user journey.

### Action Items
Automations on our site are in various levels of development. Some of them need help. Some of them are ready to use. Here's an anatomy of an automation card that tells you exactly everything you need to know about automations. (this will link to a separate guide with the anatomy)

### Resources/Instructions
#125 
[Create project anatomy guide](https://github.com/100Automations/Website/issues/128)

**Comment by NivenPrasad** [comment]
---
title: Contributing to an Automation
description: If you want to contribute to an automation, consider these tips.
status: in progress
display: true
---

## What does it mean to contribute

Instead of creating and working on your own automation, you might want to jump in and help on someone else's idea that is already in flight.

Depending on the stage of automation and what level you are, automations need different kinds of help such as: 

- refactoring 
- maintaining 
- development 
- advice 
- peer review

## How to contribute

The automation cards on our website will tell you what stage an automation is and how you can help or contribute. If you want to know more about any of the details on these cards, you can look at the [anatomy of an automation card].

All the automations to be worked on live in GitHub so if you're not set up with GitHub make sure you are before you jump into contributing.

To contribute:
- Click on the Readme for the automation on our Home page
  - Read the readme
  - Read the contributing.md for the repo
  - Look at what issues are open
  - Reach out to the owner of that repo (or as otherwise directed by the readme) to let them know you are wanting to contribute to the project!

## Who can contribute?

While the bulk of the work with an automation generally rests with developers, there might well be issues related to project management, documentation, content writing, or product management that an automation could use some help with. So if you're curious and not necessarily a developer, feel free to browse the Readme for the relevant automation for more info!

## What do you get for contributing?

The 100 Automations project gives developers visibility and credit for their work by highlighting contributor profiles on our website. 

In addition, contributing to an automation can have multiple benefits in your growth and career:
- Level up your programming skills
- Contribute meaningfully to a civic technology project
- Build mentee or mentor relationships with other developers

If you have any additional questions, please feel free to reach out to the 100 Automations team at 100automations@hackforla.org. We look forward to supporting you in your contributions!

**Comment by NivenPrasad** [comment]
Can one of the product team please review the above?

**Comment by henlatourrette** [comment]
Reviewed: It looks more than fine to me. Is there already a Guide Page for this?

**Comment by henlatourrette** [comment]
Jason suggests using this guide as a replacement for the "Builders Guide"

**Comment by superbunker** [comment]
Added to Contributors guide.
