### ISSUE TITLE
Create issue template for futureautomations

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#13]
### Overview
An issue template for automation creators to use to ensure a minimum quality standard for automations as it makes its way through the creation workflow.

### Action Items
- [x] Review templates for current automation ideas
- [x] Draft a template here in the comments
- [x] Review with various
- [x]  Add to the futureautomations repo

### Resources/Instructions
[futureautomations repo](https://github.com/100Automations/futureautomations/issues)

**Comment by ExperimentsInHonesty** [comment]
@salice @jafow @cnk @joelparkerhenderson 

We are trying to figure out what type of questions we should ask when people are suggesting ideas for automations.  Would love to have your thoughts about this.

### Possible Questions
- Overview
- Current State ("as-is" most likely something manual but could be partially automated)
- Future Development
- Action Items/Research
- Stakeholders
- Anticipated outcomes
- Resources/Instructions

What other kinds of questions should we ask?

**Comment by salice** [comment]
Maybe add language and estimate on how big the project would be?

**Comment by jafow** [comment]
> We are trying to figure out what type of questions we should ask when people are suggesting ideas for automations. Would love to have your thoughts about this.

I'd be interested to know:
- what is the "trigger" for this automation? What starts it? What is it responding to? Is it time-based (e.g. 1x/week) or event-based (e.g. someone just created a new github issue on a repo?)
- how much "manual" or custom input does it require? The best (ie the easiest to build, test, maintain, use) automations are ones that do 1 thing the same way every time based on a certain input. Would the automation be based on some kind of "manual" intervention? If so that's fine it just may be larger scope. 


A really nice framing of the question might be, "What kind of repetitive thing do you have to do often?" -- I think this could be helpful entrypoint for someone non-technical or who isn't used to thinking about how systems interact and how they can drive one another.

**Comment by NivenPrasad** [comment]
@salice @jafow @cnk @joelparkerhenderson @tylerthome

Thank you everyone for your input on this! We've come up with a refined list below for our template. Any last thoughts? 

### Possible Questions
- Overview (What kind of repetitive thing do you have to do often and what is the benefit of automating it?)
- Current State ("as-is" most likely something manual but could be partially automated)
- Future Development
- Action Items/Research
- Stakeholders
- Anticipated outcomes
- Resources/Instructions
- Language
- Automation triggers (What starts it? What's it responding to?)
  - [ ] Time-based (Specify frequency (e.g. 1x/week)
  - [ ] Event-based (e.g. someone just created a new GitHub on a repo)
- Input required (How much manual or custom input is required?)
- Project size

**Comment by NivenPrasad** [comment]
From Ops meeting 7/28
For the template: 
- Impact - who benefits and how?
- Platform
- Output (What's desired? What do we not want to see?)
Specific example:
- Automated Slack

**Comment by NivenPrasad** [comment]
Automation proposal template in the futureautomations repo now updated to include suggested changes above so now closing this issue.
