### ISSUE TITLE
Fix the positioning on the footer element

### ISSUE THREAD

**Issue by mdothman** [100Automations/Website#148]
### Overview
Positioning on the footer element needs to be fixed.

### Action Items
I created a footer, but the text is condensed all the way to the left. The Figma designs has items centered.
- [ ] Center Text and link items
- [ ] Insert the Hack for LA icon into the footer. 

###
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363)
![image](https://user-images.githubusercontent.com/75456721/107133548-3a780e00-689e-11eb-862f-72d42baea5e9.png)

### Resources
[Twitter](https://twitter.com/100automations)
[YouTube](https://www.youtube.com/channel/UCS_BOwZ5Hj3pGHN0gmx4gAA?guided_help_flow=5)

**Comment by mcspach** [comment]
<img width="1245" alt="Screen Shot 2021-02-08 at 11 38 50" src="https://user-images.githubusercontent.com/38964454/107284841-f57de400-6a23-11eb-9617-b6907f6e57a4.png">
<img width="501" alt="Screen Shot 2021-02-08 at 11 39 30" src="https://user-images.githubusercontent.com/38964454/107284847-f747a780-6a23-11eb-92ed-35f363dbc8bc.png">

-Footer is now arranged in responsive flexbox format, matching Figma
-Footer now stays at bottom of page rather than bottom of viewport
-HackforLA logo and social icons are now in assets folder
-Screenshots above show mobile and desktop appearance

-Waiting on clearance from @mdothman to put in pull request. Will put in request when other changes gave been merged to gh-pages branch on main repo.

**Comment by NivenPrasad** [comment]
- [ ] Revise so that orgs stay on same lines as themselves.
- [ ] Adjust line height to condense the text.

**Comment by Olivia-Chiong** [comment]
@mcspach and @mdothman please meet with @drubgrubby in the coming week to talk about the suggested revisions. Thanks!
