### ISSUE TITLE
Clearly define what automations are

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#155]
### Overview
We need to define what automations are and put the definition on the website so developers can better understand whether their project is an automation

### Action Items
- [ ] Define what automations mean
- [ ] Include it in the website, Wiki and Readme

**Comment by Olivia-Chiong** [comment]
Draft: Automations are packages of code that help developers to save time by preventing effort duplication. We want to get code out of code bases into replicable packages that can then be used in other projects. 

(Should we include some examples?)

**Comment by CamilaArias** [comment]
Following up on @henlatourrette message on Slack.

Developers should have a good idea of what automations are? I guess we can craft an explanation that includes why they are important in the context of open-source development, since the definition alone wouldn't provide that much value, it's an everyday term. If the goal of the addition of this explanation is to help developers know if their project is an automation maybe if can be framed in that way. We already have a pretty similar description in the about page, and the second sentence is more like one of the ways to create automations. Maybe this can be expanded into the different places automations can come from.

I don't think this should go in the hero section though, that one's dedicated to introducing the value proposition of the project, and why someone visiting the site should keep scrolling. A definition of what an automation is doesn't quite fit there, we could add it somewhere below, since we don't have any section that briefly highlights the importance of building and collaborating on automations.

**Comment by superbunker** [comment]
Existing hero text: 
_We’re building automations and micro services that improve open source development to assist the wider Civic Tech community. We welcome ideas in all stages - connect with us and let’s build 100 automations_

Change: "automations"
**tools**, code packages, software, neat stuff, gizmos....

Draft:
_We’re supporting tools and micro services to help simplify open source development for the wider Civic Tech community. We welcome ideas and projects in all stages - connect with us and let’s build 100 automations_

**Comment by henlatourrette** [comment]
We agree on the draft and the following step should be to incorporate the new text in the final pages -> Figma, developers pages.

@mdothman will change the text in the code.

**Comment by henlatourrette** [comment]
The text was updated on the website.
