### ISSUE TITLE
Research on re-sizing tool

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#170]
### Overview
We need to research building or integrating a tool for auto-image resizing that automation creators can use for their automation graphics.

### Action Items
- [ ] Research on open source resizing tools we could use
- [ ] Research on whether build own vs integrate
- [ ] Review with team

**Comment by akibrhast** [comment]
For windows , there is a tool called 'windows power tools' that's open source on GitHub which allows for mass image resizing.

For a more fully featured image editing tool that is also open source and cross platform I would recommend using [GIMP](https://www.gimp.org/),[INKSCAPE](https://inkscape.org/)

> GIMP is a cross-platform image editor available for GNU/Linux, OS X, Windows and more operating systems. It is free software, you can change its source code and distribute your changes.
> Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you with sophisticated tools to get your job done. You can further enhance your productivity with GIMP thanks to many customization options and 3rd party plugins.

> Whether you are an illustrator, designer, web designer or just someone who needs to create some vector imagery, Inkscape is for you!


### Resources
Demo - https://docs.microsoft.com/en-us/windows/powertoys/image-resizer
Installation Instruction- https://docs.microsoft.com/en-us/windows/powertoys/install

**Comment by mcspach** [comment]
Hey guys, after seeing Akib's comment I am confused about his issue.

I would be happy to discuss in the meeting.

**Comment by mcspach** [comment]
There are a few ways of implementing a solution for this issue. 

1. Add a link to a free online image editing tool that can crop the image and resave with the right resolution. 

-  Some options include Adobe PhotoshopExpress, Fotor, and Ipiccy
-  I'm not sure what the average person's learning curve would be since they are all quite easy for me to use. 
- [Ipiccy](https://ipiccy.com/) would be my choice because it is intuitive and the steps could be written out the simplest.


2. As of now, the image would be submitted with the Github template when the Automation has been approved. 
IF that step in the process were to be an html form, we could implement a plugin like [CropperJS](https://github.com/fengyuanchen/cropperjs). 
The default behavior of CropperJS saves the full image to the server, but saves a setting for displaying only a cropped portion, which is not ideal for performance. But with some reconfiguring it may be able to save only the cropped portion at the desired resolution. 


I will continue researching.

An example of what Ipiccy looks like:
<img width="1428" alt="Screen Shot 2021-03-06 at 2 34 28 PM" src="https://user-images.githubusercontent.com/38964454/110224400-27059600-7e90-11eb-8dbb-390f075558e7.png">

**Comment by akibrhast** [comment]
@mcspach The ipiccy link is broken  other than that, I just tried using it and it is indeed super intuitive and easy to use.

Also cropper.js seems super cool! I am thinking if you are planning on 'building and integrating' something that might be the way to go? It's not as if the requirements are super tight, right?

- Image must be within X*Y and X1*Y1 pixels ?
- Image must meet a X and Y resolution ?
- Image must be of either a .jpg or .png format ?

@CamilaArias @susantangux Any chance you could please enlighten us with the constraint values of X and Y . Also am I missing any of the constraints ?

**Comment by susantangux** [comment]
Is this issue related to the project card image? If so, there was some back and forth on the image size during a previous meeting. In Figma it is 372x150. Jason spoke about 744x300 but I think it was before the idea of a cropper came about? @superbunker @CamilaArias Please confirm.
Also - was wondering if the cropping outline will have the rounded corner in the upper left hand corner? @mcspach @akibrhast

**Comment by mcspach** [comment]
@akibrhast thanks for the feedback.
- link is fixed in above comment.
- yes, the requirements you listed are correct. 1. aspect ratio 2. resolution 3. format

@susantangux thanks for the reminder on proportions.
- If the image only reaches 372x150, I recommend we choose that size for smaller files.
- As far as the corners, the border radius will be done in CSS when the page loads so no need to add a radius to the corners during this step. 

Please let me know if anything here sounds wrong.

**Comment by superbunker** [comment]
The image needs to be 744x300, but will display at half that size so it stays sharp on retina screens. This could be a problem with an automated image cropping/formatting system, since a smaller image would need to be up-res'ed, making it worse quality.

**Comment by akibrhast** [comment]
>  In Figma it is 372x150. Jason spoke about 744x300 .... @susantangux https://github.com/100Automations/Website/issues/170#issuecomment-792180202

> If the image only reaches 372x150, I recommend we choose that size for smaller files. .... @mcspach https://github.com/100Automations/Website/issues/170#issuecomment-792204333

> The image needs to be 744x300, but will display at half that size so it stays sharp on retina screens.  ... @superbunker https://github.com/100Automations/Website/issues/170#issuecomment-792213795

<br>
<br>

Given the above comments from ye all. Can we make this conclusion ?
- _A submitted image will start being considered as a valid image if and only if the image size is 744x400 pixels ?_


<br>
<br>

## Resources
https://github.com/100Automations/Website/blob/gh-pages/_guides/creating-good-project-images.md

**Comment by mcspach** [comment]
The above comment seems correct to me. 

I am expecting this will lead to a new issue which involves changes to the 'creating-good-project-images guide':
- all project images submitted must now be 744x400px
- Preferably they should be at 72ppi resolution and in png format (@superbunker is this correct?)
- We need to include a link to Ipiccy in the guide and probably a screenshot with easy instructions on how to crop an image to these specifications for those who are not savvy with graphics.

**Comment by superbunker** [comment]
The project image guide has the size under "general design tips." But as far as I can tell, ppi will be ignored — it will be displayed at an effective 144ppi, no matter the saved value. 

That guide is currently at a fairly high level (design, sourcing, attribution) with the expectation of at least some graphics savvy, in particular other Hack4LA designers who might be jumping in for a quick project. The thinking was that if someone doesn't know their way around the basics, we should probably be helping them out to ensure we have high quality project images on the home page. 

We can always expand the guide or change the focus, but if it's for more general info, it would probably be best to link out to tutorials so we don't repeat the work.

**Comment by henlatourrette** [comment]
@superbunker will incorporate the selected tool into the resources of the image guide.

**Comment by superbunker** [comment]
Didn't get to revising the guide yet, but will have this done before wednesday

**Comment by superbunker** [comment]
added tools sub-section to resources -- pr #203

**Comment by Olivia-Chiong** [comment]
PR merged. Issue closed
