### ISSUE TITLE
Create Installation Requirements Guide in contributing.md

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#171]
### Overview
We need to add an installation requirements guide to the Contributing.md file for both Windows and Mac users.

### Action Items
- [ ] Add installation requirement guide to our Contributing.md
- [ ] Review with team

### Dependency
#85 

### Resources/Instructions
[SSH Guide in Create Wiki Issue](https://github.com/hackforla/product-management/issues/25)

**Comment by mdothman** [comment]
## Issue

SSH keys are an installation requirement for contributing. To include a ssh guide would be equivalent to guiding the reader through the entire installation process. Please change the issue to  installation requirements guide.

## Reasoning

For the purposes of explaining how to set up ssh keys the reader will need to have git bash installed. Git bash is the command line terminal used for setting up SSH keys. Please refer to the [documentation](https://www.atlassian.com/git/tutorials/git-bash#:~:text=Git%20Bash%20is%20an%20application,a%20Git%20command%20line%20experience.&text=Git%20Bash%20is%20a%20package,on%20a%20Windows%20operating%20system.)

## Conclusion

SSH keys are installation requirements, and to make sure people can actually set those keys up the contributing.md file should guide the user through installing git bash and then setting up their ssh keys to begin contributing to our repository.  In addition to setting up ssh keys git bash is the terminal used for all git commands.

**Comment by mdothman** [comment]
## Issue

Setting up SSH keys in order to contribute varies depending on your operating system. I will need to be writing separate instructions for Windows, Mac, and Linux users for setting up ssh keys. I suggest we create a new document called INSTALLATION.md.

## Reasoning

Having access to all programs is crucial for development. In order to ensure our developers have all the necessary tools to create products they should have a guide to refer to. This guide will include all programs needed to contribute to the repository. The guide will also have separate sections for Windows, Mac, and Linux users.

## Conclusion

Without installation guidance a brand new developer may lack necessary tools required for development. This is due to the fact of the massive quantities of programs it takes to get started in development. 

The instructions should include: VS Code, Git Bash, Terminal, Docker, Zoom, Slack, and possibly more. INSTALLATION.md would be a brilliant guide for new users on the 100 Automations website as well.

**Comment by henlatourrette** [comment]
@mdothman will also link this issue in the contributing.md pull request.

**Comment by henlatourrette** [comment]
Related to the pull request #207
