### ISSUE TITLE
Tidy up Guides page and create components on the DS

### ISSUE THREAD

**Issue by CamilaArias** [100Automations/Website#191]
## Overview
Completion of this issue will tidy up the Guides page design with final spacing and constraints, and design and create components for the table of contents.

## Action Items

- [x] Create table of contents component
   - [x] Create component for desktop. Title is "In this guide" and each subsequent item should use the `secondary` colour to show it's a clickable item. H2 and H3 headings would be shown here in order, H3s need to be indented. The table of contents floats on the right of the content container, always accessible.
   - [x] Create component for mobile, with variants, both collapsed and expanded state. This is a dropdown that sticks to the top of the screen as you scroll down, under the nav-bar. It should have an arrow pointing right when it's collapses, and pointing down when expanded. H2 and H3 indications from desktop apply here. When clicked on an item the menu should collapse and take user to that section. The dropdown needs to be scrollable to accommodate unknown number of headings in a guide.
   - [x] Add components to DS. Refer to Set Up stage on #172 for indications on this if needed.

- [x] Tidy up constraints, spacing and styles.
   - [x] Set up a container for the text of the guide and spacing between borders and table of contents.
   - [x] Create styles for guide headings, paragraphs, ordered and unordered lists. They should be under `guide/` and not mixed with our current website styles.

## Resources/Instructions
[Guides Template](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6374)
[Issue with indications on creating a component on the Design System with auto-layout and variants](https://github.com/100Automations/Website/issues/172)

**Comment by susantangux** [comment]
@CamilaArias 
Question - In the Guides with Sections page in Figma, there are no H2 and H3 headings, only H5. What to do?

I've created 3 versions of Table of Contents for the desktop, with different type size combinations. I went with the content from Akib's guides page since he said it's from an existing page, just to see how long the table of contents gets. It's pretty long. Please review the 3 versions in Figma's PM Sandbox page and let me know what you think. We could make the table of contents shorter if the subheadings are only shown when people click on the headings...

I'll wait to hear from you before creating this component.

**Comment by CamilaArias** [comment]
@susantangux there's should be at least three levels of headings in the guides, but anyway, we won't use the same headings we use on the website, we would have a different set of headings for the guides, with the same logic people will expect from writing the markdown, H1 is the biggest and H6 the smallest. Then we can see how to unify them and say, if someone puts H1 in our guide, is an H3 in our styles, or something like that. Does that make sense?

**Comment by susantangux** [comment]
Please review Table of Contents component for desktop and mobile:
![Table of Contents_Desktop Component](https://user-images.githubusercontent.com/78511203/112711398-471fe800-8e85-11eb-8a51-5e6fc32cbeed.png)
![Table of Contents_Mobile Component](https://user-images.githubusercontent.com/78511203/112711399-4a1ad880-8e85-11eb-99dd-fb2109510f6d.png)

**Comment by susantangux** [comment]
Please review updated Guide page with a new version of Table of Contents. On Wed, 3/24, we discussed moving "In This Guide" out of the right column to the top of the content. I will show the 3/24 version vs the 3/26 version for 2 guide pages below:

- **Old version of "Creating A Good Project Image" for desktop - 3/24**

![Old_Creating a Good Project Image Guide_Mar 24](https://user-images.githubusercontent.com/78511203/112711527-50f61b00-8e86-11eb-8a7a-2ea1cc2d9467.png)

- **New version of "Creating A Good Project Image" for desktop - 3/26**

![New_Creating a Good Project Image Guide_Mar 26](https://user-images.githubusercontent.com/78511203/112711535-666b4500-8e86-11eb-98e8-506f34e937fc.png)

- **This is what happens when the mouse hovers over a section in the Table of Contents:**

![New_Creating ToC_Hover Over A Section](https://user-images.githubusercontent.com/78511203/112711565-987ca700-8e86-11eb-811a-6607f62a7dc7.png)

- **This is what happens when the mouse hovers over a sub-section in the Table of Contents:**

![New_Creating ToC_Hover Over A Sub-Section](https://user-images.githubusercontent.com/78511203/112711576-a9c5b380-8e86-11eb-9aa3-b01eb2114a98.png)

- **Old version of "Self-Evaluating an Automation Idea" guide - 3/24**

![Old_Idea Self-Evaluation Guide_Mar 24](https://user-images.githubusercontent.com/78511203/112711593-d8438e80-8e86-11eb-8668-0b56e292eab4.png)

- **New version of "Self-Evaluating an Automation Idea" guide - 3/26**

![New_Idea Self-Evaluation Guide_Mar 26](https://user-images.githubusercontent.com/78511203/112711610-edb8b880-8e86-11eb-8a53-397c8400387a.png)

- **This is the mobile guide page with Table of Contents. See the Table of Contents master component for what the ToC looks like when expanded.**

![Mobile Guide Page_Mar 26](https://user-images.githubusercontent.com/78511203/112711618-01641f00-8e87-11eb-8adc-98fc8edfab6f.png)

**Comment by superbunker** [comment]
it's done!
