### ISSUE TITLE
Update Site Architecture for project

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#204]
### Overview
We need to decide on css framework and update the Site Architecture document.

### Action Items
- [x] Research and decide on CSS framework
- [x] Review with team
- [x] Remove MDL
- [x] Update Site Architecture doc
- [x] publish using MKdocs 
- [ ] Test that this answers the questions in the [guides wireframe issue](https://github.com/100Automations/Website/issues/174#issuecomment-800795569)
- [ ] Add FAQ's to document

### Resources/Instructions
[Site Architecture ](https://github.com/100Automations/Website/wiki/Site-Architecture)
Documentation will be published using mkdocs in this repo: https://github.com/100Automations/Architecture
it will publish at this url: https://100automations.github.io/Architecture

**Comment by mdothman** [comment]
I am just now beginning to rewrite the architecture document, but I do not expect it to be completed until we have finalized the site.

**Comment by mdothman** [comment]
I will have the site architecture updated to date, and the architecture will be finalized on site completion.

**Comment by henlatourrette** [comment]
hi @mdothman please share the updates on this issue. Thanks!

**Comment by superbunker** [comment]
Searchable documentation better idea than media/video for this

**Comment by superbunker** [comment]
@mdothman will drop his draft into a comment here

**Comment by mdothman** [comment]
# 100 Automations Site Architecture for Development _Update_

## Overview

Welcome to 100 Automations: a github nexus for open source development. 100 Automations was built using [Jekyll](https://jekyllrb.com/) a Ruby Gem.
In addition to the use of HTMl, CSS, and Javascript; Jekyll uses [Liquid](https://shopify.github.io/liquid/) a template language written in Ruby.

100 Automations uses [Docker](https://docs.docker.com/get-docker/) for a server.
You really only need to install Docker, be sure to become familiar with both Jekyll, and Liquid.

## Contents

1. Site components 
   1. Front-End
      1. HTML
      2. Assets
      3. _sass
         1. Components
         2. includes
         3. press-kit
   2. Back-End
      1. _data
      2. config.yml
      3.  Collections
          1. _automations
          2. _bios
          3. _guides
          4. _memes
          5. _pages

## Back-End

### Collections

Collections are markdown files that contain data.
The data contains the content for our website.

#### _automations

100 Automations is a website built to host Automations or automatic software programming.
The Automations contain only data inside of the front matter.

There is no markdown contained within the file, and thusly has no content to display.
If you want to display the data within automations you will have to iterate through the data using liquid.

```html
{% for automation in site.automations %}

<h1>
  {{automation.title}}
</h1>

{% endfor %}
```

#### _bios

If you are on the 100 Automations team, either building an automation or the website, you will be creating a bio.
Bios are like automations, they only contain front matter and contain no content in markdown.

This collection's files are viewable as an individual file and accessed through the default property `bio.url`.
This is done in the config.yml file: `output: true`.

Additionally there is a layout for each bio.

#### _guides

In addition to the front matter inside of a guide there is also markdown content.
This content is displayed accessing the default `content` property.

This file is viewable because our config.yml file states that the output of this file should be viewable.
There is also a layout under the same name that coordinates how each guide should be displayed.

#### _memes

The content for Memes is located in the front matter.
The data located in memes is the url of the static `assets/images/`

**Comment by mdothman** [comment]
# 100 Automations Site Architecture for Development

## Overview

Welcome to 100 Automations: a github nexus for open source development. 100 Automations was built using [Jekyll](https://jekyllrb.com/) a Ruby Gem.
In addition to the use of HTMl, CSS, and Javascript; Jekyll uses [Liquid](https://shopify.github.io/liquid/) a template language written in Ruby.

100 Automations uses [Docker](https://docs.docker.com/get-docker/) for a server.
You really only need to install Docker, be sure to become familiar with both Jekyll, and Liquid.

## Contents

1. Site components
   1. Front-End
      1. HTML
         1. `_includes/`
            1. `About/`
            2. `All-Guides/`
            3. `Default/`
            4. `Home/`
            5. `Press/`
            6. `toc.html`
         2. `_layouts/`
            1. `bios.html`
            2. `default.html`
         3. `index.html`
         4. `all_guides.html`
         5. `about.html`
         6. `press-kit/`
      2. `assets/`
         1. `images/`
         2. `css/`
      3. `_sass/`
         1. `index.scss`
         2. `components/`
         3. `includes/`
         4. `press-kit/`
         5. `variables/`
   2. Back-End
      1. `_data/`
      2. `_config.yml`
      3.  Collections
          1. `_automations/`
          2. `_bios/`
          3. `_guides/`
          4. `_memes/`

## Front-End

### `assets/`

This folder contains static files contained on the site.
In the `_site/` you will have all of your css and images.

Images are used throughout the site within the components with which their folders are named:

* automations
* guides
* memes
* social-media-posts

The folders `icons/` and `illustrations/` are used within the sites interface.
These folders are self-titled.

### `_sass/`

This folder conatins all of the styles and scss.
This folder is processed using jekyll's built in SASS processor.

This folder is imported into `assets/css` and used to build our _site folder.

#### `index.scss`

This is the folder directory.
Each folder has a directory that imports all files.

```scss
@import "variables/index.scss";
@import "components/index.scss";
@import "includes/index.scss";
@import "layouts/index.scss";
@import "press-kit/all_bios.scss";

```

#### `components/`

```scss
@import "buttons.scss";
@import "cards.scss";
@import "flexbox.scss";
@import "chips.scss";

```

Each component is stored and categorized in the files show above.
These are components that are mapped out across the site.

To style a component within the site check to see if already exists in the components folder.
Then use the class name in the html of your component and style.

#### `includes/`

```scss
@import "About/index.scss";
@import "All-Guides/index.scss";
@import "Default/index.scss";
@import "Home/index.scss";
@import "Press/index.scss";

```

Includes are first organized by the page that the include exists on.
When you style a page you use includes to componentize each section of the page.

Each page is built using includes and those includes contain styles for:

* Typography
* Spacing
* Layout
* Color

#### `layouts/`

```scss
@import 'guides_hero.scss';
@import 'guides.scss';

```

This example above is for styling each guide.
Each guide is displayed using the `_layouts/guides.html`.

The layouts are directly correlated to the layouts folder.
Currently the layouts that are being used are guides.

#### `press-kit/`

Press-kit is a folder located in the root of the site.
This folder contains the different sections of the Press Kit Page

*Currently the only section is the Team page* 

#### `variables/`

```scss
@import "colors.scss";
@import "typography.scss";

```

Variables are used to create a shorthand expression in place of the css code for colors and typography.

## Back-End

### `_data/`

The data folder exists for holding different data files.
Currently the only data file that is contained within the data folder is called `nav.yml`

```yml
- name: Home
  link: "/"

- name: Press
  link: press-kit/press-kit-index

- name: About
  link: about

- name: Guides
  link: all_guides

- name: Bios
  link: press-kit/all_bios

```

This creates an array of different objects containing a name and link.
The name is arbitrary, but the link is the name of the file that will be displayed.

We access these files using `{{ data.nav }}`.
For example to access `Guides` simply go to  `{{ data.nav[2] }}`.

Then you can target and display the pages name and link using the `name` and `link` properties:
`{{ data.nav[2].name }}` or `{{ data.nav[2].link }}`.

### `config.yml`

This file is necessary for middleware routing: defining collections, layouts, styles, title, and site url.
More specifically this file is necessary for Jekyll to work its magic and build our site.

If you were to reference any url's in liquid, jekyll would use the config file to create that url.
Any links to any file in your collection can be configured by jekyll using the config file. 

```yml
baseurl: ""
url: https://100automations.org

repository: 100Automations/Website

sass:
  sass_dir: _sass
  style: compressed

```

### Collections

Collections are markdown files that contain data.
The data contains the content for our website.

#### `_automations/`

100 Automations is a website built to host Automations or automatic software programming.
The Automations contain only data inside of the front matter.

There is no markdown contained within the file, and thusly has no content to display.
If you want to display the data within automations you will have to iterate through the data using liquid.

```html
{% for automation in site.automations %}

<h1>
  {{automation.title}}
</h1>

{% endfor %}
```

#### `_bios/`

If you are on the 100 Automations team, either building an automation or the website, you will be creating a bio.
Bios are like automations, they only contain front matter and contain no content in markdown.

This collection's files are viewable as an individual file and accessed through the default property `bio.url`.
This is done in the config.yml file: `output: true`.

Additionally there is a layout for each bio.

#### `_guides/`

In addition to the front matter inside of a guide there is also markdown content.
This content is displayed accessing the default `content` property.

This file is viewable because our config.yml file states that the output of this file should be viewable.
There is also a layout under the same name that coordinates how each guide should be displayed.

#### `_memes/`

The content for Memes is located in the front matter.
The data located in memes is the url of the static `assets/images/`

**Comment by mdothman** [comment]
# 100 Automations Site Architecture for Development

## Overview

Welcome to 100 Automations: a github nexus for open source development. 100 Automations was built using [Jekyll](https://jekyllrb.com/) a Ruby Gem.
In addition to the use of HTMl, CSS, and Javascript; Jekyll uses [Liquid](https://shopify.github.io/liquid/) a template language written in Ruby.

100 Automations uses [Docker](https://docs.docker.com/get-docker/) for a server.
You really only need to install Docker, be sure to become familiar with both Jekyll, and Liquid.

## Contents

1. Site components
   1. [Front-End](#Front-End)
      1. [HTML](#html)
         1. [`_includes/`](#_includes/)
            1. [`About/`](#about/)
            2. [`All-Guides/`](#all-guides/)
            3. [`Default/`](#default)
            4. [`Home/`](#home/)
            5. [`Press/`](#press/)
            6. [`toc.html`](#toc.html)
         2. [`_layouts/`](#_layouts/)
            1. [`guides.html`](#bios.html)
            2. [`default.html`](#default.html)
         3. [`index.html`](#index.html)
         4. [`all_guides.html`](#all_guides.html)
         5. [`about.html`](#about.html)
         6. [`press-kit/`](#press-kit/)
      2. [`assets/`](#assets/)
      3. [`_sass/`](#_sass/)
         1. [`index.scss`](#index.scss)
         2. [`components/`](#components/)
         3. [`includes/`](#includes/)
         4. [`press-kit/`](#press-kit-style)
         5. [`variables/`](#variables/)
   2. [Back-End](#back-end)
      1. [`_data/`](#_data/)
      2. [`_config.yml`](#config.yml)
      3.  [Collections](#collections)
          1. [`_automations/`](#_automations/)
          2. [`_bios/`](#_bios/)
          3. [`_guides/`](#_guides/)
          4. [`_memes/`](#_memes/)
          5. [`_social-media-posts/`](#_social-media-posts/)

## Front-End

### _HTML_

The HTML is responsible for displaying the site. You will build different pages, sections, and components using a combination of:

* HTML
* Javascript
* Liquid

Liquid will help with processing our back-end elements for display.
The HTML is responsible for all page building elements and for containing liquid.

Javascript is used within the site to help execute User Experiences.
Javascript can also contain back-end elements using liquid.

[^ Contents](#contents)

#### `_includes/`

An Include componenent is a section of each page within our site.
Each include folder contains several different files and an `index.html`.

`index.html` is the root directory for each folder and establishes the pages build.

[^ Contents](#contents)

##### `About/`

`index.html`:

```html
{% include About/about_one.html %}
{% include About/join_us.html %}
{% include About/acknowledgements.html %}

```

As you can see from the index file this page is built using three components.
The order in which we use our include statement is the order that these files are displayed on our page.

[^ Contents](#contents)

##### `All-Guides/`

`index.html`:

```html
{% include All-Guides/all_guides_hero.html %}
{% include All-Guides/all_guides_list.html %}

```

As you can see from the index file this page is built using two components.
The order in which we use our include statement is the order that these files are displayed on our page.

[^ Contents](#contents)

##### `Default/`

This folder contains the necessary components for our default layout.
All pages contain these default components.

[^ Contents](#contents)

##### `Home/`

`index.html`:

```html
{% include Home/action.html %}
{% include Home/wave.html %}
{% include Home/ato_grid.html %}
{% include Home/border.html %}
{% include Home/guide_grid.html %}

```

The Home page is our most populous page containing three sections and a divider component.
The divider is called `wave.html`.

`border.html` is a section containing three separate user experiences.

[^ Contents](#contents)

##### `Press/`

`index.html`:

```html
{% include Press/press_action.html %}
{% include Press/wave.html %}
{% include Press/share_ato.html %}

```

This is the press page which only has two sections for content.
If you notice, there is also a `wave.html`: just like the home page.

The `press_action.html` is a page that contains all the links to navigate the `press-kit/`

[^ Contents](#contents)

##### `toc.html`

This file is located in the includes and belongs to the guide layuout.
In read the markdown file that is being processed through jekyll we include toc.html

`toc.html` captures the jekyll variables and creates an html nav item list.

[^ Contents](#contents)

### `_layouts/`

This folder contains the layouts of each page that is in the site.
Layouts are different from includes because you can't include a layout in a page.

[^ Contents](#contents)

#### `guides.html`

Each guide has a layout that is determined by the `guides.html`
We use the `_includes/toc.html` to make a nav menu.

The `{{ content }}` is the markdown text in the markdown file.

[^ Contents](#contents)

#### `default.html`

This is the default layout for every page. Every page needs a header, footer, title, head element, and html body and container elements.
The `{{ content }}` for this layout are all the pages that we have in the root directory.

[^ Contents](#contents)

### `index.html`

```html
---
layout: default
title: Home
---

{% include Home/index.html %}

```

The Home page.

[^ Contents](#contents)

### `all_guides.html`

```html
---
layout: default
title: All Guides Page
---

{% include All-Guides/index.html %}


```

All Guides page.

[^ Contents](#contents)

### `about.html`

```html
---
layout: default
title: About Page
---

{% include About/index.html %}

```

[^ Contents](#contents)

### press-kit/

```html
---
layout: default
title: Press-Kit Page
---

{% include Press/index.html %}

```

The `press-kit/` is a folder that imports the `includes/Press` to display the press page.
It also contains the team page `all_bios.html`.

[^ Contents](#contents)

### `assets/`

This folder contains static files contained on the site.
In the `_site/` you will have all of your css and images.

Images are used throughout the site within the components with which their folders are named:

* automations
* guides
* memes
* social-media-posts

The folders `icons/` and `illustrations/` are used within the sites interface.
These folders are self-titled.

[^ Contents](#contents)

### `_sass/`

This folder conatins all of the styles and scss.
This folder is processed using jekyll's built in SASS processor.

This folder is imported into `assets/css` and used to build our _site folder.

[^ Contents](#contents)

#### `index.scss`

This is the folder directory.
Each folder has a directory that imports all files.

```scss
@import "variables/index.scss";
@import "components/index.scss";
@import "includes/index.scss";
@import "layouts/index.scss";
@import "press-kit/all_bios.scss";

```

[^ Contents](#contents)

#### `components/`

```scss
@import "buttons.scss";
@import "cards.scss";
@import "flexbox.scss";
@import "chips.scss";

```

Each component is stored and categorized in the files show above.
These are components that are mapped out across the site.

To style a component within the site check to see if already exists in the components folder.
Then use the class name in the html of your component and style.

[^ Contents](#contents)

#### `includes/`

```scss
@import "About/index.scss";
@import "All-Guides/index.scss";
@import "Default/index.scss";
@import "Home/index.scss";
@import "Press/index.scss";

```

Includes are first organized by the page that the include exists on.
When you style a page you use includes to componentize each section of the page.

Each page is built using includes and those includes contain styles for:

* Typography
* Spacing
* Layout
* Color

[^ Contents](#contents)

#### `layouts/`

```scss
@import 'guides_hero.scss';
@import 'guides.scss';

```

This example above is for styling each guide.
Each guide is displayed using the `_layouts/guides.html`.

The layouts are directly correlated to the layouts folder.
Currently the layouts that are being used are guides.

[^ Contents](#contents)

#### `press-kit-style`

Press-kit is a folder located in the root of the site.
This folder contains the different sections of the Press Kit Page.

This folder is for styling the subpages of the press-kit page.

[^ Contents](#contents)

#### `variables/`

```scss
@import "colors.scss";
@import "typography.scss";

```

Variables are used to create a shorthand expression in place of the css code for colors and typography.

[^ Contents](#contents)

## Back-End

### `_data/`

The data folder exists for holding different data files.
Currently the only data file that is contained within the data folder is called `nav.yml`

```yml
- name: Home
  link: "/"

- name: Press
  link: press-kit/press-kit-index

- name: About
  link: about

- name: Guides
  link: all_guides

- name: Bios
  link: press-kit/all_bios

```

This creates an array of different objects containing a name and link.
The name is arbitrary, but the link is the name of the file that will be displayed.

We access these files using `{{ data.nav }}`.
For example to access `Guides` simply go to  `{{ data.nav[2] }}`.

Then you can target and display the pages name and link using the `name` and `link` properties:
`{{ data.nav[2].name }}` or `{{ data.nav[2].link }}`.

[^ Contents](#contents)

### `config.yml`

This file is necessary for middleware routing: defining collections, layouts, styles, title, and site url.
More specifically this file is necessary for Jekyll to work its magic and build our site.

If you were to reference any url's in liquid, jekyll would use the config file to create that url.
Any links to any file in your collection can be configured by jekyll using the config file. 

```yml
baseurl: ""
url: https://100automations.org

repository: 100Automations/Website

sass:
  sass_dir: _sass
  style: compressed

```

[^ Contents](#contents)

### Collections

Collections are markdown files that contain data.
The data contains the content for our website.

[^ Contents](#contents)

#### `_automations/`

100 Automations is a website built to host Automations or automatic software programming.
The Automations contain only data inside of the front matter.

There is no markdown contained within the file, and thusly has no content to display.
If you want to display the data within automations you will have to iterate through the data using liquid.

```html
{% for automation in site.automations %}

<h1>
  {{automation.title}}
</h1>

{% endfor %}
```

[^ Contents](#contents)

#### `_bios/`

If you are on the 100 Automations team, either building an automation or the website, you will be creating a bio.
Bios are like automations, they only contain front matter and contain no content in markdown.

This collection's files are viewable as an individual file and accessed through the default property `bio.url`.
This is done in the config.yml file: `output: true`.

Additionally there is a layout for each bio.

[^ Contents](#contents)

#### `_guides/`

In addition to the front matter inside of a guide there is also markdown content.
This content is displayed accessing the default `content` property.

This file is viewable because our config.yml file states that the output of this file should be viewable.
There is also a layout under the same name that coordinates how each guide should be displayed.

[^ Contents](#contents)

#### `_memes/`

The content for Memes is located in the front matter.
The data located in memes is the url of the static `assets/images/`

[^ Contents](#contents)

#### `_social-media-posts/`

The images for social media posts is also located in the `assets/images/`.
However each document in social media posts is for each social media network.

```
---
have-an-idea: 
    src: assets/images/social-media-posts/FB-have-an-idea.png
    alt: Have an Idea?
host-automation: 
    src: assets/images/social-media-posts/FB-host-automation.png
    alt: Host An Automation
logo: 
    src: assets/images/social-media-posts/FB-logo.png
    alt: logo
social: Facebook

---

```

This is the social media posts that we have for Facebook.
The other documents in the collection reference different images for their social media website.

[^ Contents](#contents)

**Comment by mdothman** [comment]
# 100 Automations Site Architecture for Development *Update*

## Overview

Welcome to 100 Automations: a github nexus for open source development. 100 Automations was built using [Jekyll](https://jekyllrb.com/) a Ruby Gem.
In addition to the use of HTMl, CSS, and Javascript; Jekyll uses [Liquid](https://shopify.github.io/liquid/) a template language written in Ruby.

100 Automations uses [Docker](https://docs.docker.com/get-docker/) for a server.
You really only need to install Docker, be sure to become familiar with both Jekyll, and Liquid.

## Contents

1. Site components
   1. [Front-End](#Front-End)
      1. [HTML](#html)
         1. [`_includes/`](#_includes/)
            1. [`About/`](#about/)
            2. [`All-Guides/`](#all-guides/)
            3. [`Default/`](#default)
            4. [`Home/`](#home/)
            5. [`Press/`](#press/)
            6. [`toc.html`](#toc.html)
         2. [`_layouts/`](#_layouts/)
            1. [`guides.html`](#bios.html)
            2. [`default.html`](#default.html)
         3. [`index.html`](#index.html)
         4. [`all_guides.html`](#all_guides.html)
         5. [`about.html`](#about.html)
         6. [`press-kit/`](#press-kit/)
      2. [`assets/`](#assets/)
      3. [`_sass/`](#_sass/)
         1. [`index.scss`](#index.scss)
         2. [`components/`](#components/)
         3. [`includes/`](#includes/)
         4. [`press-kit/`](#press-kit-style)
         5. [`variables/`](#variables/)
   2. [Back-End](#back-end)
      1. [`_data/`](#_data/)
      2. [`_config.yml`](#config.yml)
      3.  [Collections](#collections)
          1. [`_automations/`](#_automations/)
          2. [`_bios/`](#_bios/)
          3. [`_guides/`](#_guides/)
          4. [`_memes/`](#_memes/)
          5. [`_social-media-posts/`](#_social-media-posts/)

## Front-End

### _HTML_

The HTML is responsible for displaying the site. You will build different pages, sections, and components using a combination of:

* HTML
* Javascript
* Liquid

Liquid will help with processing our back-end elements for display.
The HTML is responsible for all page building elements and for containing liquid.

Javascript is used within the site to help execute User Experiences.
Javascript can also contain back-end elements using liquid.

[^ Contents](#contents)

#### `_includes/`

An Include componenent is a section of each page within our site.
Each include folder contains several different files and an `index.html`.

`index.html` is the root directory for each folder and establishes the pages build.

[^ Contents](#contents)

##### `About/`

`index.html`:

```html
{% include About/about_one.html %}
{% include About/join_us.html %}
{% include About/acknowledgements.html %}

```

As you can see from the index file this page is built using three components.
The order in which we use our include statement is the order that these files are displayed on our page.

[^ Contents](#contents)

##### `All-Guides/`

`index.html`:

```html
{% include All-Guides/all_guides_hero.html %}
{% include All-Guides/all_guides_list.html %}

```

As you can see from the index file this page is built using two components.
The order in which we use our include statement is the order that these files are displayed on our page.

[^ Contents](#contents)

##### `Default/`

This folder contains the necessary components for our default layout.
All pages contain these default components.

[^ Contents](#contents)

##### `Home/`

`index.html`:

```html
{% include Home/action.html %}
{% include Home/wave.html %}
{% include Home/ato_grid.html %}
{% include Home/border.html %}
{% include Home/guide_grid.html %}

```

The Home page is our most populous page containing three sections and a divider component.
The divider is called `wave.html`.

`border.html` is a section containing three separate user experiences.

[^ Contents](#contents)

##### `Press/`

`index.html`:

```html
{% include Press/press_action.html %}
{% include Press/wave.html %}
{% include Press/share_ato.html %}

```

This is the press page which only has two sections for content.
If you notice, there is also a `wave.html`: just like the home page.

The `press_action.html` is a page that contains all the links to navigate the `press-kit/`

[^ Contents](#contents)

##### `toc.html`

This file is located in the includes and belongs to the guide layuout.
In read the markdown file that is being processed through jekyll we include toc.html

`toc.html` captures the jekyll variables and creates an html nav item list.

[^ Contents](#contents)

### `_layouts/`

This folder contains the layouts of each page that is in the site.
Layouts are different from includes because you can't include a layout in a page.

[^ Contents](#contents)

#### `guides.html`

Each guide has a layout that is determined by the `guides.html`
We use the `_includes/toc.html` to make a nav menu.

The `{{ content }}` is the markdown text in the markdown file.

[^ Contents](#contents)

#### `default.html`

This is the default layout for every page. Every page needs a header, footer, title, head element, and html body and container elements.
The `{{ content }}` for this layout are all the pages that we have in the root directory.

[^ Contents](#contents)

### `index.html`

```html
---
layout: default
title: Home
---

{% include Home/index.html %}

```

The Home page.

[^ Contents](#contents)

### `all_guides.html`

```html
---
layout: default
title: All Guides Page
---

{% include All-Guides/index.html %}


```

All Guides page.

[^ Contents](#contents)

### `about.html`

```html
---
layout: default
title: About Page
---

{% include About/index.html %}

```

[^ Contents](#contents)

### press-kit/

```html
---
layout: default
title: Press-Kit Page
---

{% include Press/index.html %}

```

The `press-kit/` is a folder that imports the `includes/Press` to display the press page.
It also contains the team page `all_bios.html`.

[^ Contents](#contents)

### `assets/`

This folder contains static files contained on the site.
In the `_site/` you will have all of your css and images.

Images are used throughout the site within the components with which their folders are named:

* automations
* guides
* memes
* social-media-posts

The folders `icons/` and `illustrations/` are used within the sites interface.
These folders are self-titled.

[^ Contents](#contents)

### `_sass/`

This folder conatins all of the styles and scss.
This folder is processed using jekyll's built in SASS processor.

This folder is imported into `assets/css` and used to build our _site folder.

[^ Contents](#contents)

#### `index.scss`

This is the folder directory.
Each folder has a directory that imports all files.

```scss
@import "variables/index.scss";
@import "components/index.scss";
@import "includes/index.scss";
@import "layouts/index.scss";
@import "press-kit/all_bios.scss";

```

[^ Contents](#contents)

#### `components/`

```scss
@import "buttons.scss";
@import "cards.scss";
@import "flexbox.scss";
@import "chips.scss";

```

Each component is stored and categorized in the files show above.
These are components that are mapped out across the site.

To style a component within the site check to see if already exists in the components folder.
Then use the class name in the html of your component and style.

[^ Contents](#contents)

#### `includes/`

```scss
@import "About/index.scss";
@import "All-Guides/index.scss";
@import "Default/index.scss";
@import "Home/index.scss";
@import "Press/index.scss";

```

Includes are first organized by the page that the include exists on.
When you style a page you use includes to componentize each section of the page.

Each page is built using includes and those includes contain styles for:

* Typography
* Spacing
* Layout
* Color

[^ Contents](#contents)

#### `layouts/`

```scss
@import 'guides_hero.scss';
@import 'guides.scss';

```

This example above is for styling each guide.
Each guide is displayed using the `_layouts/guides.html`.

The layouts are directly correlated to the layouts folder.
Currently the layouts that are being used are guides.

[^ Contents](#contents)

#### `press-kit-style`

Press-kit is a folder located in the root of the site.
This folder contains the different sections of the Press Kit Page.

This folder is for styling the subpages of the press-kit page.

[^ Contents](#contents)

#### `variables/`

```scss
@import "colors.scss";
@import "typography.scss";

```

Variables are used to create a shorthand expression in place of the css code for colors and typography.

[^ Contents](#contents)

## Back-End

### `_data/`

The data folder exists for holding different data files.
Currently the only data file that is contained within the data folder is called `nav.yml`

```yml
- name: Home
  link: "/"

- name: Press
  link: press-kit/press-kit-index

- name: About
  link: about

- name: Guides
  link: all_guides

- name: Bios
  link: press-kit/all_bios

```

This creates an array of different objects containing a name and link.
The name is arbitrary, but the link is the name of the file that will be displayed.

We access these files using `{{ data.nav }}`.
For example to access `Guides` simply go to  `{{ data.nav[2] }}`.

Then you can target and display the pages name and link using the `name` and `link` properties:
`{{ data.nav[2].name }}` or `{{ data.nav[2].link }}`.

[^ Contents](#contents)

### `config.yml`

This file is necessary for middleware routing: defining collections, layouts, styles, title, and site url.
More specifically this file is necessary for Jekyll to work its magic and build our site.

If you were to reference any url's in liquid, jekyll would use the config file to create that url.
Any links to any file in your collection can be configured by jekyll using the config file. 

```yml
baseurl: ""
url: https://100automations.org

repository: 100Automations/Website

sass:
  sass_dir: _sass
  style: compressed

```

[^ Contents](#contents)

### Collections

Collections are markdown files that contain data.
The data contains the content for our website.

[^ Contents](#contents)

#### `_automations/`

100 Automations is a website built to host Automations or automatic software programming.
The Automations contain only data inside of the front matter.

There is no markdown contained within the file, and thusly has no content to display.
If you want to display the data within automations you will have to iterate through the data using liquid.

```html
{% for automation in site.automations %}

<h1>
  {{automation.title}}
</h1>

{% endfor %}
```

[^ Contents](#contents)

#### `_bios/`

If you are on the 100 Automations team, either building an automation or the website, you will be creating a bio.
Bios are like automations, they only contain front matter and contain no content in markdown.

This collection's files are viewable as an individual file and accessed through the default property `bio.url`.
This is done in the config.yml file: `output: true`.

Additionally there is a layout for each bio.

[^ Contents](#contents)

#### `_guides/`

In addition to the front matter inside of a guide there is also markdown content.
This content is displayed accessing the default `content` property.

This file is viewable because our config.yml file states that the output of this file should be viewable.
There is also a layout under the same name that coordinates how each guide should be displayed.

[^ Contents](#contents)

#### `_memes/`

The content for Memes is located in the front matter.
The data located in memes is the url of the static `assets/images/`

[^ Contents](#contents)

#### `_social-media-posts/`

The images for social media posts is also located in the `assets/images/`.
However each document in social media posts is for each social media network.

```
---
have-an-idea: 
    src: assets/images/social-media-posts/FB-have-an-idea.png
    alt: Have an Idea?
host-automation: 
    src: assets/images/social-media-posts/FB-host-automation.png
    alt: Host An Automation
logo: 
    src: assets/images/social-media-posts/FB-logo.png
    alt: logo
social: Facebook

---

```

This is the social media posts that we have for Facebook.
The other documents in the collection reference different images for their social media website.

[^ Contents](#contents)

**Comment by superbunker** [comment]
site architecture repository:
https://github.com/100Automations/Architecture

**Comment by mdothman** [comment]
# 100 Automations Site Architecture -  _Update_

## [MKDocs Live Site](https://100automations.github.io/Architecture/)
