### ISSUE TITLE
Tracking Issue for PM CoP

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#276]
### Overview
We want to have an issue where all CoP product managers can submit their thoughts and review of the 100 Automations website.

### Action Items
Please view the website at https://100automations.github.io/Website/ and provide your thoughts on the homepage.
1. What do you think the purpose of the website is?
2. How do you think the website can be improved? (Functionality or Design recommendations both welcome)

### Resources/Instructions
Please provide your answers in the comments below.

**Comment by alexilee** [comment]
1. What do you think the purpose of the website is?
To source developers to work on 100 Automation projects and to get new ideas from the community.

2. How do you think the website can be improved? (Functionality or Design recommendations both welcome)
- Inconsistent/out-of-date fonts (e.g. top right navigation, Creator Overview page, etc.)
- Website layout could be modernized and follow better design principles (Contents sidenav design can look nicer and sidenavs are usually on the left with a border or different section of color)
- There are a lot of guides to read, maybe too many. It's a strange experience to have some guides on the website while some guides are in GitHub
- The overall intended flow is a bit confusing. For example, I am not a developer yet the first call to action is the contribute button on the homepage. Can I contribute even though I am not a developer? Is the website only looking for developers to contribute? The overall navigation and information architecture could be improved. There seem to be a lot of hidden pages that cannot be accessed from the home page.
- Automations and Guides button on the top right don't seem to do anything for me
- The About page does not use any padding or margins
- How can I view all automations that have been completed or in progress? I don't think I was able to find this unless the only ones are the two from the homepage. If so, a note to the user might be helpful to let them know it's an emerging project

**Comment by connie-yu-dotcom** [comment]
1. To give developers an opportunity to add to automatons and share.
2.  -The font on the top right nav doesn't match the rest of the site, it should be consistent.
     -Image quality for "jekyll data gather type" is low res and it needs to be improved.
     -the color squares for "Guides" is not homepage consistent. It doesn't fit the site.

**Comment by mariastudnicka** [comment]
What do you think the purpose of the website is?
To source developers to work on 100 Automation projects and to get new ideas from the community.

How do you think the website can be improved? (Functionality or Design recommendations both welcome)

I'm going to +1 on Alex's comments on inconsistencies in layout and fonts.
I realize I'm not the target audience, I'm not understanding the value proposition. There are sources that I found that exist in github such as github.com/rest-assured for use. Is this meant for peer review as well?
I'm totally lost on what the cards are supposed to represent. What does "need help" mean?
The nav links don't work for automation and guides. : <
Is there a reason to have a press release? Would contact us suffice?
This is a preliminary 1st pass at this exercise.

**Comment by Arjayellis** [comment]
1. What do you think the purpose of the website is?
- Source ideas and give developers a place to contribute to automations 
2. How do you think the website can be improved? (Functionality or Design recommendations both welcome)
- Mobile is clunky. Dynamic image overlaps with the words and some assets could be resized
- Inconsistency with fonts
- Guides section is a bit "busy" in terms of coloring. Not a fan of the fonts
- About page needs padding
- Maybe too many goals? 
- The Acknowledgements could use some borders or separation
- Buttons on the about page should match the button on the homepage (they look Windows 95ish)
- The Press page is confusing and a bit visually strange (assuming this is being worked on already) 
- Link issues for me
  - Once I go to the About or Press page, I am not able to navigate back to Automations without clicking the logo at the top left
  - Clicking Guides does not do anything for me

What I do like:
- Primary color scheme 
- Logo is rad
- Moving gears
- The mission

**Comment by nagesh23nayak** [comment]
First of all great work. Just some comments

What do you think the purpose of the website is?
To help people with getting things getting automated especially for people who have ideas but lack background in development.

How do you think the website can be improved? (Functionality or Design recommendations both welcome)
Need to Add some Use cases which explains by giving example
Reduce content in guide and make it simple.
Reduce transition to github
Make fonts consistent
A lot of space is being wasted on top near rotating wheels which could have some content
Links on top right corner don't work as needed
Some links have 'End of File'. Not sure if that's needed.
Contents section in links is on right side. Maybe they could be left aligned or more vibrant. It looks like a hyperlink in word document.
I lack knowledge about jekyll and I was trying to understand the purpose of that section.

**Comment by DrIffathsultana** [comment]
What do you think the purpose of the website is?
To source developers to work on 100 Automation projects and to get new ideas from the community.

How do you think the website can be improved? (Functionality or Design recommendations both welcome)
- Too much of information on pages.
- Navigation should be more simplified and easier to understand the process as a new user.
- When a user clicks on any link, then it should open on a different page, because sometimes you get lost which page you were on.
- Fonts are too big and inconsistent.
- Color schema for guides needs improvement. 

I like the moving gear -COOL

**Comment by natenateo** [comment]
Hi Brave Reader,
Thank you for all of your hard work and for being willing to ask for feedback!
1. There are three use cases: 1. ideation 2. sr. developer 3. jr. developer. 
2. I suggest that you help visitors self-identify into each category.

Ex. What role fits you best? 
- Ideator - I have an idea
- Sr. Developer - I can do it myself
- Jr. Develop - I might need help

Hope this helps! Lmk if you have any questions.

**Comment by erigilg** [comment]
The purpose of the website? The purpose of 100 automations is to automate recurring activities to make things easier in the civic tech community. 

How can it be improved? 

I didn't notice there was a menu on the upper right side of the site. 
I don't really get what microservices is, what do you mean with let's build 100 automations? 
An image, animation or mock up would work great! As an example. 
Why does the call to action says contribute, I feel that is for contributing with money. 
I'm not sure I understand how to use it. What does the needs help tab, is it that the automation is incomplete? 
The texts in the cards are difficult to read. Too much text, probably use bullet points. 
Didn't notice that the need help was clickable. 
The submit your automation stripe makes it easier for me to understand how 100 automations work. I would move that upward. Also, I would change the title from submit to participate or something that englobes the three activities for engaging.
The guides part stands out as something very different from the rest

**Comment by kcoronel** [comment]
Great work 100 Automations Team! 

_1. What do you think the purpose of the website is?_
The purpose of the site is to give potential volunteers information about 100 automations project and to provide a page to collect ideas and volunteers. 

_2. How do you think the website can be improved? (Functionality or Design recommendations both welcome)_

This paragraph is great, I have a slight inclination it can use an introductory paragraph maybe like: 
**“Thought out by a team of volunteers from HackforLa, 100 Automations is a**… A project that showcases automations and microservices that reduce repetitive work in open source development; a project where anyone can create, collaborate on, and get credit for open source automations that assist the wider Civic Tech community. 100Automations welcomes ideas in all stages, from the half-baked to the fully researched, as well as anything in between.

Some spacing between goals so that the images and wording are equally spaced out and white space is available. “Find and promote currently unknown automation authors” is written twice 

Spacing in Acknowledgements

Special Mentions change validate use cases to validating use cases 

I had trouble navigating the right hand pages 

Make all guides unison, for the Supporting Your Automation with Community it looks like the contents font is different 

I didn't know Needs Help was clickable 

I also think that the Submit Your Automation should move up on the page

**Comment by Andan-Eddy** [comment]
The automations and guides buttons on top right of home page don't seem to work

More "about" this project early would be good- still getting head around purpose- may simply be targeted at sophisticated audience 

redundancy in why is there a Needs help: Test card and Jekly Gateher Data types

I thought Contribute was asking for money

stylistically Guides section doesn't fit 

Needs Help- is not obviously clickable - should maybe move within larger box below

**Comment by ggrrettcchhenn** [comment]
- Top navigation a) doesn't seem to be connected (except About) and b) doesn't match the font of the rest of the site
- The grid of Guide buttons at the bottom of the homepage doesn't match the rest of the design (gradient instead of flat, different colors, blue underline)
- Define automation on homepage - the word is used so often and it's not obvious exactly what it means. Are they like plugins? bits of code? what languages are they in? (I'm not a programmer, maybe this is more obvious to programmers). I like the 
   - Are there any complete automations? It would be helpful to see them on the homepage to get a sense of what this project has to offer
- There seem to be a lot of links on the pages. Would be helpful to have a robust list of grouped links in the footer, or submenu items to navigate around.
- External links should open in new window. (Or maybe these should be linked to the Guide page on the website instead of the github page)
- On About page, "Automations" & "Website" contribution buttons aren't linked, and neither are the project links
- Add margin/border space on About page
- "Using an Automation" guide is just a template, no content
- Unordered & ordered lists and contents tables on Guides pages are using a different font than the rest of the site
- "Suggest a Guide" button isn't linked on homepage
- Didn't know "Needs Help" was clickable on the automation cards – would be good to add a chevron style arrow to indicate that it's clickable, or add it as a button near the ReadMe.

**Comment by ag2463** [comment]
What do you think the purpose of the website is?
To give an overview of the 100 Automations project and to get ideas of things that could be automated.

How do you think the website can be improved? (Functionality or Design recommendations both welcome)
- the menu on the top right was not obvious
- the 'needs help' button was not clear that it was clickable
- Also agree that the fonts/color scheme could be simplified

**Comment by NivenPrasad** [comment]
[Synthesized feedback ](https://docs.google.com/document/d/1V1EaQt3ghBrAEjPn1uz-aJuwSfsQsKo6HEloS6faQX8/edit#)by @CamilaArias 
(Note there was additional feedback on Friday 4.30 that hasn't yet been incorporated into that feedback doc.)

**Comment by henlatourrette** [comment]
We need to create issues labeled Bug from the feedback - where applicable

**Comment by NivenPrasad** [comment]
All the issues from the synthesized feedback have been converted to issues where applicable. So this issue I believe can now be closed.

**Comment by superbunker** [comment]
All set!
