### ISSUE TITLE
Hack for Your Mother Feedback on May 8th, 2021

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#296]
### Overview
This issue is to gather information on the feedback we get from the "Hack For Your Mother" Hackaton.

### Action Items
- [x] Write information from the feedback we get at the Hackaton.
- [x] Identify noted bugs and if issues have been resolved yet
- [x] create issues for open bugs

### Resources/Instructions

bugs and issues
- [x] Guides colors look weird - _fixed_
- [x] Swirly white bit persists when scrolling down - _fixed_
- [x] Lot of empty space on a big screen from Hero Page - _in progress_
- [x] Didn't realize "Needs Help" is a button - _in progress_
- [x] every guide says "Learn best practice for creating a good project image" - **bug!** #339

suggestions and ideas:
- Rabbit hole of guides - it's a lot of reading before you even submit an idea
- The form should be priority rather than having to read so much to finally submit an idea
- a list of automations 
- Search for your idea, see if there's others like it already
- voting on ideas
- Sign-in flow for a new user
- Permissions for people who have submitted ideas
- Unclear which stage person creates repo

**Comment by NivenPrasad** [comment]
**Feedback on Website and Submitting Form**

Really great colors and generally liked the website
Liked the Readme button
Really liked the Submit Your Automation section - very well done - colors, layout, and copy
Guides colors look weird - don't necessarily match the scheme. Blue lines should
Swirly white bit persists when scrolling down
Lot of empty space on a big screen from Hero Page
Didn't realize Needs Help is a button - one solution might be that the cursor changes but that's not viable if you're on mobile
In this guide - project image
Want to know how to start creating automations:
Lot of plain stuff without letting you know what to do
Breadcrumb to let you go back home - can get lost

- In This Guide - every guide says "Learn best practice for creating a good project image"
- Self-evaluating Guide - currently goes to GitHub page - all the links should be

- Rabbit hole of guides - it's a lot of reading before you even submit an idea - 5-10min video might be better or easier to go into submitting form and go into a "play" mode rather than. Guidelines and what you should expect.

- The form should be priority rather than having to read so much to finally submit an idea

**Feedback on form**:
  - Current state question at bottom of form - maybe should be dropdown
  - Platform - what does this mean? We need to clarify
  - Some more direction on how long it might take to build the automation - give direction on effort and time - guidelines on
  - Can you save something with a Google Form? You might partly fill it out and want to come back to it later
  - Will these be free/open-source free? Will there be costs associated with this project?
  - Once you submit form, thank you page and a link to see your idea on the board. Since you're capturing email, can we email them the summary so they can remember what their idea was
  - Emails should be deleted so they're not in the issue
  - Issue should go straight to project board?
  
**Future Ideas for the Project**
  - How might we make a list of automations visible to a website visitor
  - Search of your idea - map it against the current ideas to see if others are working on this kind of idea
  - Voting on current ideas that are in progress
  - How does a contributor
  - How might we move a lot of these cards/workflow to the website where contributors can use? Maybe a way that those events are mirrored on the back-end. Sign-in flow for a user 
  - Upvote a person's idea on here
  
**Futureautomations Project Board**

- Permissions for people who have submitted ideas
- Can we make template/example cards under each column?
- Unclear which stage person creates repo
   - Can we create template repo that creator
   
  Another automation idea
  - Batch automation where you can take that info and add to the Readme

**Comment by superbunker** [comment]
Jean F. Queralt - The IO Foundation JFQueralt@TheIOFoundation.org
https://github.com/TheIOFoundation/ProjectLockdown

Making github into full project management suite
Project Lockdown
https://github.com/TheIOFoundation/ProjectLockdown
too many labels!
labels a good to attach, but become a hindrance in the interface
converting labels to keyword/hashtags

Automation Ideas:

**cross-repo issue flags**
open source projects that needs to scale need more than developers - they need accountants, HR, non-github users

**github project template**

**TechUp** - monthly event, next one is next weekend (may 15)
https://TIOF.Click/EventsCal
https://TIOF.Click/EventsRSVP
offer to us: Airtable - free booth, 48 hour event

public-facing repo, and a private version 



qpage.one - hr platform, paid 
using github to monitor work


automation: creating wiki for a fork via pages in a repo

extracting data from salesforce import into airmeet

g calendar doesn't work like gdrive - there's a script forces a change

a way for projects to signal across github that they'd like to come onboard, via a label or something

big fan of appsumo.com

**Comment by henlatourrette** [comment]
Adding on Jean's suggestions:
- Google Calendar Automator to update calendar to new members.
- Contributions to Wiki doesn't get counted on GitHub. Is this like that?
- Automation to look on GitHub Across Repositories.

**Comment by henlatourrette** [comment]
We need to review this issue and create new issues from the feedback.

**Comment by superbunker** [comment]
Got the bugs turned in to issues or fixed.
