### ISSUE TITLE
Update the CSS for the guides

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#334]
### Overview
We need to fix the CSS styling in the  guide pages.

### Action Items
- [x] Review CSS in  guide pages
- [x] Debug issues
- [x] Update CSS
- [x] Review with team
- [x] Deploy code

### Resources/Instructions
[Website](https://100automations.github.io/Website/)

**Comment by NivenPrasad** [comment]
@Clue355 - the Guide pages mobile version isn't completely up to date yet so talk to @mdothman when you get the chance about the break points in the mobile version of the individual guides pages.

**Comment by superbunker** [comment]
updated: this for the global guides styles

**Comment by mcspach** [comment]
@Clue355 please leave a comment here with multiple screenshots and a reference to your branch. I dont have much time but here's a few comments:

-There is no breakpoint, so the current styling only works above 700px width.
-Line 16 in guides.html should read not be hard-coded text, it should be {{page.description}}
-When you change that, you may have to refactor lines 100-102 in guides.scss
-Check the sizing on the table of contents div, I think it currently has a max-height and the text overflows on some guides.
-I personally think this page would be better dealt with using flex-box than grid. But that's just my preference
-If you stick with grid, change the table of contents to take up a full row on mobile, and change the orientation of your grid so that the table of contents div comes first in the html.
-There is a horizontal scrollbar, let's find out why and get rid of it.
-check out the following screenshots... Are we intentionally leaving so much space on the righthand side?

<img width="1001" alt="Screen Shot 2021-06-16 at 11 51 39 AM" src="https://user-images.githubusercontent.com/38964454/122276020-38037180-ce99-11eb-8f86-2dd74fe82eb3.png">
<img width="1424" alt="Screen Shot 2021-06-16 at 11 51 54 AM" src="https://user-images.githubusercontent.com/38964454/122276071-43569d00-ce99-11eb-9b9e-466c49ec2dcd.png">

PS: the mobile styling for the table of contents looks complicated, feel free to leave that alone for now and we can make that it's own issue.

**Comment by henlatourrette** [comment]
After the latest Merge, we need to update the width issues and the grey background from the menu.

**Comment by henlatourrette** [comment]
Carlos is doing a Pull Request for @superbunker or @mdothman to review it

**Comment by mdothman** [comment]
- [x] Header needs styling for mobile: Title should be smaller and span entire page.
- [x] Side Margins need to be reduced.
- [x] Nav menu drawer needs to be created for mobile.

**Comment by superbunker** [comment]
closed enough
