### ISSUE TITLE
Marketing review of mvp site content plan

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#37]
### Overview
Identify what marketing assets we need to support the project objectives

### Dependancy
#78 

### Action Items
- [x] Ask Marketing what content needs to be added to the website to support its marketing efforts
- [ ] Ask Marketing to review the activities we are trying to support

### Background

- 100 Automations website will be public facing.
- It is in MVP site design at the moment and we were about to turn it over to development soon when we realized that we had not asked what would we need in order to promote this, and where that should that live on the site. 

The types of activities we want to support from the start:

- Individual contributors who are publicizing the automations that have been launched on our website
- People who hear about the idea and want to promote it
- Press that want to feature it
- Promotion we will do ourselves (initial site launch, recruiting for developers to do automation submissions, hitting milestones on our way to our goal, etc.)

### Resources/Instructions
[Current site design in Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

Press kit page: https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=791%3A30

**Comment by ExperimentsInHonesty** [comment]
https://github.com/100Automations/Website/issues/40

**Comment by NivenPrasad** [comment]
Notes from marketing meeting on 10.10.20:
- Went through the MVP website designs
- Went through user groups in [issue 40](https://github.com/100Automations/Website/issues/40)
- What are the categories of things to include in the Press Kit? So that designer knows what else to include in Press Kit page
- Downloadable press kit would be nice - much easier for PR people 
- One-sheet for press - if you're speaking to the NY Times, what is it that they'd want to know?
- Press release for each project would be an ideal vision for the future
- Get into a habit for having an announcement for each project - hope is that media starts following each one

**Comment by philippricefry** [comment]
Would rename this page "Press" 

Suggested layout for this specific page (in order of hierarchy on page):

1: Press Releases & Media Alerts (should drop down OR open to another page where releases will be both downloadable and archived OR can open to a Google Drive)
2: Assets (should drop down OR open to another page OR open to a google drive where media can download things like logos, bios, fact sheets, etc.)
3: Contact 100 Automation's Press Office: Copy to go underneath: "Are you a member of the media? Please send us a note at Press@hackforla.com or x email" (we can decide this later)
4: Share what we're doing! (Should open to another page OR open to a google drive where there are downloadable social assets for media &/or consumers &/or contributors)
5: Featured in: (can be at the bottom of the page where it shows links to recent press - should not click open to another page)

Questions for @ExperimentsInHonesty : 
The above I think absolutely should be part of this page. The below are two things I want to suggest but may not be necessary because they could love on another part of the site.

1: Leadership OR Collaborators: Often times media will want to know "Okay, so who is working on this and running it?". Do we want to shine light on leaders of this specific project? If the answer is yes, this part would be called "Leadership" or "Collaborators" and would feature bios + names of the people that media should know. If the answer is "No, we do not need this", I will make sure that the "fact sheet" in the assets part of the Press page outlines that this is a Hack for LA project managed by a LOT of different people. 

2. FAQ: Sometimes I like to add a FAQ page that would essentially answer every obvious answer (obvious to us, prob not obvious to an outsider) a consumer and journalist would have. The lens is - it's for a journalist, but often times consumers will come through here. May not be necessary but always a nice to have. 

Unrelated bonus question: DO we want to create a "Press" email for HackForLa? Where is the best place for a journalist to reach out if they have a question? Should we create project specific forums or one general inbox that can be fielded by myself and another manager or two?

**Comment by NivenPrasad** [comment]
Great feedback! Discussed with @CamilaArias @ExperimentsInHonesty on 10.14.
Assigning now to Design to start framing contents for Press page, which should be the following:
1. Press releases 
2. Assets section - with icons for Logos, Bios, Fact Sheets etc
3. Section for Contact 100 Automations Press Office with copy: "Are you a member of the media? Please send us a note at 100Automations@hackforla.org"
4. Section (or button) called Share 100 Automations! (Drop down)
5. Section called Featured In - links on the page to recent press

**Comment by NivenPrasad** [comment]
@CamilaArias once mock-ups are done, we will send to Philip for review.

**Comment by CamilaArias** [comment]
- Banner for social media: open source development (include our logo)

**Comment by NivenPrasad** [comment]
@CamilaArias is working on making it so that you can make the two interfaces consistent, in relation to being able to share the memes.

**Comment by ExperimentsInHonesty** [comment]
Pinterest uses the download icon as the way to navigate to share

**Desktop Pinterest**
![Screen Shot 2020-11-28 at 3 57 44 PM](https://user-images.githubusercontent.com/37763229/100528499-8158d180-3192-11eb-982b-343b83873ded.png)

Mobile
![Screen Shot 2020-11-28 at 3 57 32 PM](https://user-images.githubusercontent.com/37763229/100528501-8453c200-3192-11eb-9d15-d47d2ea4b121.png)

**What is behind the  "..." on the primary page**  - which is different from the ... on the share page
![Screen Shot 2020-11-28 at 3 57 20 PM](https://user-images.githubusercontent.com/37763229/100528502-84ec5880-3192-11eb-8cbe-df139c4ab05e.png)

**Comment by NivenPrasad** [comment]
Progress: @CamilaArias has reviewed the above comment.
Blocks: None.
Availability: Available.
Eta: Saturday

**Comment by Olivia-Chiong** [comment]
This is being paused due to  investigation of #78

**Comment by NivenPrasad** [comment]
Investigation of #78 concluded - all the images will need 2 icons:
1. One for sharing
2. One for download

**Comment by NivenPrasad** [comment]
Need:

- Content for Bios page 
- Content for Fact Sheet
- Press release

Once we have that content, @CamilaArias can do mock-ups of the Bios page and Fact Sheet (could be a page or modal). @Olivia-Chiong will make issues for the Fact Sheet, Bios page, and Press Release (or ensure they exist) and link them here in this issue.

**Comment by Olivia-Chiong** [comment]
Bio pages - #86 
Fact Sheet - Is one of the action items on #55 
Press Release - #55

**Comment by Olivia-Chiong** [comment]
Paused pending #87

**Comment by superbunker** [comment]
This is an early stage discussion, superseded by several press page issues
