### ISSUE TITLE
Create a guide: Writing an Article about your Automation

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#48]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Writing an Article about your Automation" guide.

### Action Items
- [x] Review True GitHub Contributors article outline and create a guideline for how to write an article 
- [x] Write mark-down for the guide instructions in a comment on this issue.
- [x] Create a mark-down file for this guide and add it to a folder called _guides
   - [x] Call the file a name with dashes that is as short as possible
      - [x] name: writing-articles-for-automations.md
   - [x] Add the following header to the file:
```
---
title: Writing an Article about your Automation
description: 
status: coming soon
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)
[Reference articles for what should be in the article](https://medium.com/@timmalstead) 
[True GitHub Contributors article outlines](https://docs.google.com/document/d/1y0XIlpqPzVSrBtM6ganAzW7Sn3A7Pa4NtEitoE0GD7I/edit)

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty @nahyungkim1220 and @KianBadie to meet and review True Github Contributors article together.

**Comment by nahyungkim1220** [comment]
Draft 1: https://docs.google.com/document/d/1Vi74RhpZn2U8o79iimO6KesKRaY2zip-F0ANKxTq1go/edit

**Comment by nahyungkim1220** [comment]
###  How to Write an Article About Your Automation
#### Tell your journey like it’s a story. What challenges did you run into? How did you try to tackle them? Ultimately, what resolution did you come to? 
#### Tips: Break down big chunks of information under headlines. Always give examples (snippets of code) when you can.

- **Title:** Should be short and straight to the point, preferably not longer than 20 words.
o	Title can describe what your code does (i.e.”Create a team roster with Node.js, React, and Google Sheets”)
- **Subtitle**:
o	Optional, but a very good space to summarize how your code makes your life easier: (i.e. “Create and update your team’s page with ease”) 
- **Opening paragraph**: 
o This can be short and sweet. 
o You can begin this opening with anything - add your personal touch to this opening, but make sure to relate it back to your automation. 
o You can open your article with why you began developing your project.
- **Body**: 
-	Tell the journey of how you developed your code, and break it down into different stages; 
o	What problems/issues did you see? Why did you decide to address them?
o	How did you go about overcoming the challenges? (i.e. onboarding, communication, challenges within your code)
o	How would the reader implement your automation (what preparation do they need to make? Break this down into steps.)
- **Closing:** Finally, end the article with a summary of your thoughts, possible future improvements, or what you learned from this journey.

**Comment by nahyungkim1220** [comment]
---
title: Writing an Article for Your Automation
description: If you want to write an article about your automation, consider these tips on content and structure.
status: in progress
display: true
---

# Writing an Article for Your Automation
If you're thinking about writing an article about your automation, start here!
A great article increases your visibility as a developer, and opens room for peer review. 
It also gives users detailed examples on ways to use your code.

## General Tips
- Provide links to references or background knowledge if possible.
- Explain jargons when you use them so that beginners can understand your process.

## Keywords
- SEO tips that could help articles show up on top of search engines (needs more research)

## Language & Readability
- It's always a good idea to double-check for spelling and grammar before publishing. 
- Use spelling and grammar checkers, such as [Grammarly](https://www.grammarly.com/grammar-check).
- Break down long sentences and paragraphs. [Hemmingway](http://hemingwayapp.com/) is a great readability tool that flags complicated sentences.
- Spell out acronyms the first time you use them. 
1. Example: HfLA (Hack for LA)
- Before publishing, ask for an extra pair of eyes to read over your article.

## Title
- The title is short (less than 25 words) and gives a solution to a problem. 
- The title should grab the reader's attention.

- Good Examples ([Writing technical articles: tips for programmers - Dev](https://dev.to/iriskatastic/writing-technical-articles-tips-for-programmers-29gp)): 
1. Ensuring healthy Node.js program using watchdog timer 
2. Adaptive Components & Parent-Driven Behavior in Angular
3. How to Make HTTP Requests In React

- Bad Examples:
1. Roundup #58: Orleans 3.0, Snitch, What’s Your Problem? Next 5 years of ASP.NET Core
2. The One Code to Rule Them All
3. Suffering From Technical Debt?

## Subtitle
- The title grabs your reader's attention, and the subtitle invites them to read further.
- The subtitle expands on details you couldn't put in your title.
- Examples of Titles and Subtitles:
1. 
2.
3.

## Header Image
- Provide an image of the final outcome of your code. This will help save time for readers who are scrolling looking for specific solutions.

## Introduction
- Briefly explain in what your automation does, why it's useful, what problem(s) it solves.
- Introduce how you came to create your automation or how you decided to address a particular problem. 
- If your article is longer than a page, consider creating a table of contents ater your Introduction.

## Body
- Briefly explain how to set up your automation.
- Give examples of how your automation can be used in different programs.
- You know the saying: a picture is worth a thousand words. Give visualizations (screenshots, end results, illustrations, workflow charts, etc.) to back up your explanations and break up large blocks of text. The more relevant pictures you have in your article, the better you'll be able to get your points across.
- Separate large blocks of text under headings.

## Conclusion
- As you close the article, briefly summarize your article.
- Key takeaways from this project: 
- Open room for discussion or suggestions for potential improvements that could be made to your automation.

**Comment by nahyungkim1220** [comment]
Created a mark-down file for this guide and added it to a folder called _guides: [Writing an Article for Your Automation](https://github.com/100Automations/Website/blob/master/_guides/writing-articles-for-automations.md)

**Comment by Olivia-Chiong** [comment]
@nahyungkim1220 to contact Ben Swerdlow about article writing.

**Comment by NivenPrasad** [comment]
Hi @nahyungkim1220 - I've reviewed the PR and requested one minor edit.
