### ISSUE TITLE
Write Bio - Site Builder: Camila Arias

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#66]
### Overview
We need some info to put on our site about you, so that we can market the site.

### Action item
- [x] Provide 
   - [x] Name
   - [x] Bio: _A 1-2 paragraph professional bio_
   - [x] Quote:  _A quote from you about automations_
   - [x] Motivations
      - [x] Internal:  _What are your internal motivations for building the site?_
      - [x] External: _What are your external motivations for building the site?_
   - [x] Picture - _Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by CamilaArias** [comment]
Name: Camila Arias

Bio: I'm a Jack of all Trades, I like learning and experimenting in different disciplines. I enjoy solving problems for people and making things work better, and getting involved in any of the phases of building those solutions. I've got a background in Electronics and Programming, so when I began studying Multimedia Design in Uni, I coded games, art installations, augmented reality experiences,... Then I started doing more design and I ended up freelancing as Visual and Graphic Designer. Last couple years I've been working on UI/UX Design, and participating on projects that allow me to get experience also as a Product Manager, and collaborating closely with Engineering, Biz Dev and QA. I also enjoy working with remote international teams and meeting awesome people!

Quote:
If you can do it once, an automation can do it forever!

Internal:
I joined to get more experience as a designer in a bigger, cross-functional team, and because I loved the idea of 100 Automations.

External:
It's exciting to think how much of an impact this project could make, the contributions to 100 Automations can potentially generate a constantly expanding impact that we can't tell how far it could go! Many civic-tech projects and beyond could leverage the automations built and streamline progress thanks to this project.

[LinkedIn](https://www.linkedin.com/in/camila-arias/)
