### ISSUE TITLE
Investigate Sharethis Package

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#78]
### OVERVIEW
We need to understand the limitations and constraints of ShareThis for the purpose of sharing the images to social media and downloading them.

### ACTION
- [ ] Dev to investigate using ShareThis for social media and download buttons on images.
- [ ] Create a shortlist of what we can control or identify what is clearly defined in the documentation and provide a link to it.
- [ ] Answer if we will be able to provide a download link as part of the ShareThis or if we need to provide this before/parallel to it.

### RESOURCES
[ShareThis](https://sharethis.com/)

**Comment by mdothman** [comment]
# Investigative report on ShareThis Package

## Overview
For a quick and easy installation on your site, you can simply copy and paste the code from [ShareThis](https://platform.sharethis.com/). If you want to share something that isn't inline, picture, video, or the page itself, you can create a custom button for sharing whatever you like.

## Heads Up
**You always need the code in the header of HTML**
>       <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=#{property?._id}&product=custom-share-buttons"></script>
>
>
**What the package does**
* Share: Social media, Blogs, Email, and Print
    * Primarily the functions of the buttons that you are able to select have a data network set up already.
    * This means that you will only be able to use these networks:
        * blogger
        * delicious
        * digg
        * email
        * facebook
        * flipboard
        * googleplus
        * linkedin
        * livejournal
        * mailru
        * meneame
        * odnoklassniki
        * pinterest
        * print
        * reddit
        * sharethis
        * sms
        * stumbleupon
        * tumblr
        * twitter
        * vk
        * weibo
        * whatsapp
        * xing
**What you need to do**

* Copy and paste:
    * Simply go to [ShareThis](https://platform.sharethis.com/) and start creating your own share buttons. When you have created the buttons to your specifications, just click on *Activate Code* in the top left hand corner of the window. 
    * Once you have followed those steps, paste your newly composed code into your HTML <head> tag.


* Custom Buttons
    * [How to create custom buttons](https://sharethis.com/support/customization/how-to-set-custom-buttons/)

    * Follow the guide as instructed:
        * You can change the HTML, CSS, and Js for the button.

**HTML explained:**         
>           
>           <div data-network="twitter" class="st-custom-button">Twitter</div>
**Javascript explained:**
>        (function(document) {
>           */ shareButtons is an array of classes "st-custom-button[data-network]"
>            data-network is the value of each index of the array:
>            example: "twitter"
>           /*   
>            var shareButtons = document.querySelectorAll(".st-custom-button[data-network]");
>             for(var i = 0; i < shareButtons.length; i++) {
>                 var shareButton = shareButtons[i];
>      
>        //After looping through our array of buttons we add an event listener that logs the network value.
>        //Notice that network is accessed through each elements dataset? network is the value of the dataset.
>        shareButton.addEventListener("click", function(e) {
>         var elm = e.target;
>         var network = elm.dataset.network;
>        
>         console.log("share click: " + network);
>                });
>            }
>        })(document);
>

**Other data attibutes**
* > data-url 
  * A specific url you can share
* > data-short-url 
  * A shortened url for use in conjunction with data-url
* > data-title 
  * Specifies title you want shared
* > data-image 
  * Specifies link to image you would like displayed in the shared content
* > data-description 
  * Summary text/description you wish to share
* > data-username 
  * Specifies your twitter username
* > data-message 
  * Specifies the body copy of e-mail shares

**Conclusion**
1. You can create custom buttons that carry custom share functions for sharing specified data attributes, including network.
   
2. You can't use ShareThis for a custom download button because download is not apart of their data network.@ [Step 2](https://platform.sharethis.com/custom-share-buttons)
   
3. Custom buttons are used to transverse different medium (pictures, video, text), and design their appearance (hidden, border-radius, opacity)
   
4. ShareThis is an API for Sharing.
   
5. Create a download button that will be parallel to the share button (If you want a download button). Then plug in your share buttons.

**Comment by ExperimentsInHonesty** [comment]
This is great research with the finding that we will need to have the download button in addition to the social share button.

**Comment by mdothman** [comment]
@ExperimentsInHonesty Thank you, I will be editing to include more information on custom data-attributes: attaching a description, tags, title, etc.

**Comment by mdothman** [comment]
I updated the report just now. I have included additional information on data-attributes, and a link, provided by ShareThis, to a coding sanding box for visualization.  I also reported my observations when working with the code in my own coding sandbox.  I worked on images specifically for our purposes.

**Comment by Olivia-Chiong** [comment]
This tool is not going to work, we are going to look at other tools.
